### ISSUE TITLE
OSError and timeouts

### ISSUE THREAD

**Issue by RobertRosca** [reiserm/midtools#5]
When I was trying to run the examples from the test branch, I frequently ran into errors like:

```python
OSError: Timed out trying to connect to 'tcp://10.255.32.50:35106' after 10 s:
Timed out trying to connect to 'tcp://10.255.32.50:35106' after 10 s: connect() didn't finish in time
```

Where the communication between workers on different nodes would sometimes fail. I'm not too sure why this is happening.

I used a new `venv` for the installation of MIDTools, and the issue would occur less often if I lowered the number of workers and nodes, however the processing never ran consistently for me with the settings provided in the test branch.

The best I could get was 100 trains with 8 jobs and 8 procs instead of 12, bumping it to 12 it would fail (seemingly) all the time.

Troubleshooted this a bit and it seemed like the errors happened more often if the jobs were being submitted from an allocated node (instead of a login node), and maybe they happened more often when the GPFS scratch (`/gpfs/data/scratch/...`) directory was used instead of the home directory, but these are pretty weak observations since I didn't test it out very much.

**Comment by RobertRosca** [comment]
Steps I used to create the venv, install xana, and install midtools:

```
cd ~/scratch/roscar/work/  # symlink to my gpfs scratch dir
mkdir reiserm && cd reiserm

#  gh is GitHubs neat CLI tool, I'd do it this way but I've commented that out
#  and used normal git clone instead
# gh repo clone reiserm/midtools
# gh repo clone reiserm/Xana
git clone https://github.com/reiserm/midtools.git
git clone https://github.com/reiserm/Xana.git

python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools

pip install -e './Xana'
pip install -e './midtools'

mkdir tmp && cd tmp
wget https://raw.githubusercontent.com/reiserm/midtools/dask-tests/tests/setup_dask_good.yml
```

Now, if I run `midtools ./setup_dask_good.yml 11 -r 201 -ppt 100 --last 100` on
a login node the output is like:

<details>
  <summary>Full terminal output, click to expand</summary>

```
❯ midtools ./setup_dask_good.yml 11 -r 201 -ppt 100 --last 100
Development Mode

--------------- Starting Analysis ----------------
Analyzing 100 trains of /gpfs/exfel/exp/MID/202022/p002693/proc/r0201

-----------------------META-----------------------
1043 of 1091 trains are complete.
100 of 1091 trains will be processed.

-------------------DIAGNOSTICS--------------------
Read XGM data.

Submitting 12 jobs using 12 processes per job.
SLURMCluster('tcp://10.255.32.50:40745', workers=0, threads=0, memory=0 B)
Cluster dashboard link: http://10.255.32.50:8787/status
Requesting data...
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
Loaded dask array.
Is processed: True
Apply masking

----------------------FRAMES----------------------
Computing frames.
Start computation
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
[########################################] | 100% Completed | 19.9s
-----------------------SAXS-----------------------
Compute pulse resolved SAXS
Start computation
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 322, in connect
    _raise(error)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 275, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.255.32.50:40745' after 10 s: connect() didn't finish in time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/bin/midtools", line 33, in <module>
    sys.exit(load_entry_point('midtools', 'console_scripts', 'midtools')())
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/dataset.py", line 813, in main
    data.compute()
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/dataset.py", line 574, in compute
    f"_compute_{method.lower()}")()
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/dataset.py", line 632, in _compute_saxs
    **saxs_opt)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/azimuthal_integration.py", line 149, in azimuthal_integration
    progress(arr)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 444, in progress
    TextProgressBar(futures, complete=complete, **kwargs)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 124, in __init__
    loop_runner.run_sync(self.listen)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/utils.py", line 497, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 67, in listen
    self.scheduler, **(self.client().connection_args if self.client else {})
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 334, in connect
    _raise(error)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 275, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.255.32.50:40745' after 10 s: Timed out trying to connect to 'tcp://10.255.32.50:40745' after 10 s: connect() didn't finish in time
```

</details>

So I see quite a few errors, mostly split between:

```
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError
```

Or:

```
OSError: Timed out trying to connect to 'tcp://10.255.32.50:40745' after 10 s: Timed out trying to connect to 'tcp://10.255.32.50:40745' after 10 s: connect() didn't finish in time
```


And if I allocate a node and then I get the same behaviour:

<details>
  <summary>Full terminal output, click to expand</summary>

    /gpfs/e/da/s/ros/w/r/tmp-alloc ❯ midtools ./setup_dask_good.yml 11 -r 201 -ppt 100 --last 100
Development Mode

--------------- Starting Analysis ----------------
Analyzing 100 trains of /gpfs/exfel/exp/MID/202022/p002693/proc/r0201

-----------------------META-----------------------
1043 of 1091 trains are complete.
100 of 1091 trains will be processed.

-------------------DIAGNOSTICS--------------------
Read XGM data.

Submitting 12 jobs using 12 processes per job.
SLURMCluster('tcp://10.255.33.250:37933', workers=0, threads=0, memory=0 B)
Cluster dashboard link: http://10.255.33.250:8787/status
Requesting data...
Loaded dask array.
Is processed: True
Apply masking

----------------------FRAMES----------------------
Computing frames.
Start computation
[########################################] | 100% Completed | 27.9s
-----------------------SAXS-----------------------
Compute pulse resolved SAXS
Start computation
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 322, in connect
    _raise(error)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 275, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.255.33.250:37933' after 10 s: connect() didn't finish in time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/bin/midtools", line 33, in <module>
    sys.exit(load_entry_point('midtools', 'console_scripts', 'midtools')())
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/dataset.py", line 813, in main
    data.compute()
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/dataset.py", line 574, in compute
    f"_compute_{method.lower()}")()
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/dataset.py", line 632, in _compute_saxs
    **saxs_opt)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/midtools/midtools/azimuthal_integration.py", line 149, in azimuthal_integration
    progress(arr)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 444, in progress
    TextProgressBar(futures, complete=complete, **kwargs)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 124, in __init__
    loop_runner.run_sync(self.listen)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/utils.py", line 497, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 67, in listen
    self.scheduler, **(self.client().connection_args if self.client else {})
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 334, in connect
    _raise(error)
  File "/gpfs/exfel/data/scratch/roscar/work/reiserm/.venv/lib64/python3.6/site-packages/distributed/comm/core.py", line 275, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.255.33.250:37933' after 10 s: Timed out trying to connect to 'tcp://10.255.33.250:37933' after 10 s: connect() didn't finish in time
❯ hostname
max-exfl180.desy.de

</details>

This was done without raising ulimit. If I run `ulimit -n 4096` then the same behaviour happens.

Can you see anything I do wrong during the setup of the environment/packages? It's a bit odd that it works for you with `setup_dask_good.yml`, but fails for me with the oserrors quite consistently.

If I lower the number of workers and nodes a bit then it fails... less often, but still fails occasionally due to the communication issues to workers. If I leave the configuration unchanged it fails seemingly every time, and I've tested it around 5 times.

**Comment by reiserm** [comment]
Did you try this with `midtools` from the master branch or with the `dask-tests` version? 

You could try to comment out the chunk size settings in the setupfile or use the setupfile here

`/gpfs/exfel/exp/MID/202022/p002693/scratch/reiserm/datasets/setup_template.yml`

In terms of the installation,  I did exactly the same as you.
